[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "vunit-python-bridge"
version = "0.1.0"
description = "A VUnit package making Python callable from VHDL."
urls = {homepage = "https://github.com/ru551n/vunit-python-bridge"}
readme = "README.md"
license = "MPL-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
authors = [
  {name = "Lars Asplund", email = "lars.anders.asplund@gmail.com"}
]
keywords = ["vunit", "vunitpkg", "verification", "vhdl", "fpga", "asic", "python", "vhpi", "vhpidirect", "fli"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
  "Natural Language :: English",
  "Intended Audience :: Developers",
]
dependencies = [
  "numpy",
  "vunit_hdl>=5.0.0.dev12",
]

[tool.setuptools]
# Don't include files in the wheel unless specified in [tool.setuptools.package-data].
include-package-data = false

[tool.setuptools.packages.find]
# Search for Python packages (directories containing __init__.py) starting at this point.
where = ["src"]

# Only include the Python package named "vunit_python_bridge".
# This prevents accidentally packaging unrelated directories.
include = ["vunit_python_bridge"]

[tool.setuptools.package-data]
# Declare non-Python files that should be included inside the vunit_python_bridge
# Python package in both the wheel and the sdist. All paths are relative to the
# vunit_python_bridge/ package directory.
vunit_python_bridge = [
  "vunit_pkg.toml",
  "vhdl/src/*.vhd",
  "vhdl/src/*.vhd.in",
  "vhdl/src/*.c",
  "vhdl/src/*.h",
  "vhdl/tools/*.vhd.in",
  "vhdl/tools/*.py",
  "native/*.c",
  "native/*.h",
  "bin/*.dll",
]

[tool.black]
line-length = 120

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
